### ISSUE TITLE
Server Error TypeError: teams.filter is not a function

### ISSUE THREAD

**Issue by akayer19** [tomasherrera1910/nba-webapp#1]
Hi Tomas!

I get an error when running. Hopefully I can attach. 

[localhost.pdf](https://github.com/tomasherrera1910/nba-webapp/files/9855730/localhost.pdf)

**Comment by tomasherrera1910** [comment]
> Hi Tomas!
> 
> I get an error when running. Hopefully I can attach.
> 
> [localhost.pdf](https://github.com/tomasherrera1910/nba-webapp/files/9855730/localhost.pdf)

you would have to get a key from sportsdata.io and create a .env.local with the variable KEY_NBA_API I would leave mine public but the monthly requests are very limited, anyway this app is just being started. sorry for my english, I know I have to work it 😂

**Comment by akayer19** [comment]
I’ll try that. I have a key already, just didn’t understand the .env.local
part.

**Comment by akayer19** [comment]
I think I got it now.  I see all the teams.

**Comment by akayer19** [comment]
User error
